global using System.ComponentModel;
global using Common.Enums;
global using Common.Extensions;
global using Common.Models.Shared;
global using DataAccess;
global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;