global using System.Diagnostics.CodeAnalysis;
global using System.Net;
global using System.Text.Json;
global using Common;
global using Common.Helpers;
global using Common.Logging.Static;
global using Common.Models.Shared;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
