/**
 * .NET Vertical Slice Minimum Architecture API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagingArgs } from './pagingArgs';


/**
 * @type BaseSearchModelPagingArgs
 * @export
 */
export type BaseSearchModelPagingArgs = PagingArgs;

