/**
 * .NET Vertical Slice Minimum Architecture API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortDirection } from './sortDirection';
import { BaseSearchModelPagingArgs } from './baseSearchModelPagingArgs';


export interface GetAllPizzasQuery { 
    OrderBy?: string;
    SortDirection?: SortDirection;
    Ordering?: string;
    PagingArgs?: BaseSearchModelPagingArgs | null;
    Name?: string | null;
}
export namespace GetAllPizzasQuery {
}


