/**
 * .NET Vertical Slice Minimum Architecture API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PagingArgs { 
    PageNumber?: number;
    PageSize?: number;
    SkipAmount?: number;
    UsePaging?: boolean;
}

