/**
 * .NET Vertical Slice Minimum Architecture API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PizzaModel { 
    Id?: number;
    Name?: string;
    DateCreated?: string | null;
    Disabled?: boolean | null;
}

