/**
 * .NET Vertical Slice Minimum Architecture API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PizzaModel } from './pizzaModel';


export interface ResultOfIEnumerableOfPizzaModel { 
    IsError?: boolean;
    IsValidationError?: boolean;
    Data?: Array<PizzaModel> | null;
    Count?: number;
    Message?: string;
    Errors?: Array<string>;
    ValidationErrors?: { [key: string]: Array<string>; };
}

