/**
 * .NET Vertical Slice Minimum Architecture API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PizzaModel } from './pizzaModel';


/**
 * @type ResultOfPizzaModelData
 * @export
 */
export type ResultOfPizzaModelData = PizzaModel;

