/**
 * .NET Vertical Slice Minimum Architecture API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type SortDirection = 'Ascending' | 'Descending';

export const SortDirection = {
    Ascending: 'Ascending' as SortDirection,
    Descending: 'Descending' as SortDirection
};

